version: '3'
services:
  app:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - mypostgres
  mypostgres:
    build: ./database/
    ports:
     - "5433:5433"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=nextgendb
     - SCHEMA=public
     